### ISSUE TITLE
Integration with EF

### ISSUE THREAD

**Issue by pe4aiko** [chriseldredge/Lucene.Net.Linq#10]
Hi! Can you tell me if there is any usage of EF or with the database without DbContext? I've red the documentation and didn't saw the information.

**Comment by chriseldredge** [comment]
Lucene.Net.Linq uses Lucene.Net's Directory to store data and has no association with EF. If you want to use Lucene.Net.Linq with data that is in a SQL database, you would need to get the data into Lucene on your own first.

**Comment by pe4aiko** [comment]
Thanks.
