### ISSUE TITLE
Update document. Is it correct?

### ISSUE THREAD

**Issue by pe4aiko** [chriseldredge/Lucene.Net.Linq#11]
Hi. I have the document with Id ([NumericField(Key = true)]).
For example I have 10 documents. If I insert document, I have 11 documents in session.
But if I update document, I will have 1 document in session.

using (var session = LuceneDataProvider.OpenSession<TEntity>())
            {
                var doc = session.Query().First(x => x.Id == id);
                doc.Relevance++;
                session.Add(doc);
            }

I use Lucene.Net 3.0.3 and Lucene.Net.Linq 3.1.46.0
I'm doing something wrong?

**Comment by chriseldredge** [comment]
Do you have a complete code sample I can review? It's hard to tell why things are going wrong with the limited sample and description.

**Comment by pe4aiko** [comment]
I find the problem. This code puts to session only one element:
var doc = session.Query().First(x => x.Id == id);

So if I want to get the document and don't change the list of documents I need to it with another way:
luceneDataProvider.AsQueryable<TEntity>().First(x => x.Id == content.Id);

**Comment by chriseldredge** [comment]
If you are not going to modify documents, using AsQueryable will be faster for retrieving them, but both should work. However, if you add a document to a session, you cannot retrieve it using session.Query() until the session is committed.
