### ISSUE TITLE
Support for TermVector and Boosting in the FieldAttribute

### ISSUE THREAD

**Issue by hydr** [chriseldredge/Lucene.Net.Linq#12]
If would be great if the FieldAttribute and the FieldMapper would support the setting of a TermVector and a Boost value. Right now we're using these settings on some fields and they don't seem to be supported by the POCO <-> document mapping.

In our document we have the command:

```
doc.Add(new Field("MediumName", model.MediumName, Field.Store.YES, Field.Index.ANALYZED, Field.TermVector.YES) {Boost = 2f});
```

**Comment by chriseldredge** [comment]
Boost is easy to support. I can add an attribute property for TermVector support, but how would you retrieve the information from LINQ? Pseudo code samples or real code welcome.

**Comment by chriseldredge** [comment]
See [TermVectorTests.cs](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Integration/TermVectorTests.cs) for an example of how to retrieve term vectors.

**Comment by hydr** [comment]
Thanks for the quick reaction! I will try out your changes in the next days and report on my success! :+1:
