### ISSUE TITLE
Example not compiling

### ISSUE THREAD

**Issue by dittodhole** [chriseldredge/Lucene.Net.Linq#19]
A `FieldAttribute` does not have a `bool` property `Store`, rather a `StoreMode` property `Store`, so:

```
Store = true
```

should be

```
Store = StoreMode.Yes
```

Also, there is no `PorterStemAnalyzer`-class in the bundle, but a `KeywordAnalyzer`-class and `StandardAnalyzer`-class.

And, you should include the implementation of `VersionConverter`-class!

**Comment by chriseldredge** [comment]
I've moved sample code into cs files so they will stay up to date now. Fixed in cdbc4bccb83701a828a8dd2bdaa7f3ade8c32a5a.
