### ISSUE TITLE
Support a fluent interface

### ISSUE THREAD

**Issue by richardgavel** [chriseldredge/Lucene.Net.Linq#22]
I would like to see a fluent interface be available for configuration so the classes that represent index items do not require attributes and have a dependency on the Lucene.Net.Linq assembly.

**Comment by chriseldredge** [comment]
Can you provide some sample pseudo code for what you would like this to look like? Or reference some other fluent configuration examples in other projects?

**Comment by richardgavel** [comment]
Good examples would be something like Fluent NHibernate. See it's getting started guide at https://github.com/jagregory/fluent-nhibernate/wiki/Getting-started.

**Comment by chriseldredge** [comment]
Added this in a75851a978e824176dd00edfe40502610f546f28. I'll close this issue after releasing to nuget.org.

**Comment by chriseldredge** [comment]
Released in 3.1.51 (https://nuget.org/packages/Lucene.Net.Linq/3.1.51)
