### ISSUE TITLE
Performance - Use TotalHits instead of ScoreDocs.length when computing Count()/Any()

### ISSUE THREAD

**Issue by gshark4321** [chriseldredge/Lucene.Net.Linq#26]
Count()/Any() are implemented using ScoreDocs.length. This means for a query such as Documents.Count(), all the metadata for each doc needs to be loaded by lucene.
If the TotalHits field were used instead, you would only have to request a single record in the search, which should improve performance greatly for large indexes.

eg) 
var hits = indexSearcher.Search(query, null, 1, new Sort())
return hits.TotalHits;

instead of:

var hits = indexSearcher.Search(query, null, int.MaxValue, new Sort())
return hits.ScoreDocs.Length

**Comment by chriseldredge** [comment]
Thanks for the tip. This has been committed in e6954b4b4ed42859e77b161fc5a7144136e7c005. I'll close this issue after releasing to nuget.org.

**Comment by chriseldredge** [comment]
Released in 3.1.51 (https://nuget.org/packages/Lucene.Net.Linq/3.1.51)
