### ISSUE TITLE
IObjectMapper extension points

### ISSUE THREAD

**Issue by mcintyre321** [chriseldredge/Lucene.Net.Linq#3]
First of all, thanks for your project, it's almost exactly what I have been looking for. Now for that almost :)

I was wondering if you could add some extension points to the object mapping code, so that I could:

a. define custom search/storage keys based on things other than properties of the object
b. override the re-materialization process

I want to do this as I am trying to use your library to provide search capabilities for my custom object database. My db objects are POCO and don't even have their own Id properties - these are stored in an external lookup. I need to be able to put these id's into the search index, so when I retrieve the data, I can use the stored id to find the original object using my db, and return that, rather than the reconstructed object.

I have tried forking so I could do this myself, but I am getting a compile error about a missing ../build/version.cs file.

**Comment by chriseldredge** [comment]
VersionInfo.cs is generated by psake.ps1.

I think both suggestions are useful and I tried to structure the code so that object/document mapping can be replaced or customized, but haven't exposed methods of swapping out replacements for the default reflection/attribute based mappers. Is your project public so I can look at it and get a better understanding of how it should work?

**Comment by mcintyre321** [comment]
There is a stub for the Indexer in my project at: https://github.com/mcintyre321/PieDb/blob/master/PieDb/Indexer.cs

The dynamic properties I am wanting to store along with the data are attached in PieIdExtension.cs, which uses a WeakReferenceTable to attach the database metadata to the object. it is this data which I need to retrieve after querying, so I can look up my objects.

**Comment by mcintyre321** [comment]
It looks like some way to override or add extra steps into the following methods would do the trick:

ReflectionDocumentMapper.ToDocument - then one could add extra items into the document
LuceneQueryExecutor.ConvertDocument - then one can replace or extend the object mapping process

Looking at the code, there are several ways to do this, the most obvious being to allow inherited types of the above classes, but that will involve making a lot of classes public. It might be worth just having a couple of delegates (e.g. ToDocumentDelegate, ConvertDocumentDelegate) properties on the LuceneDataProvider which can be replaced, which have default implementations the same as the methods.

One other suggestion - could the : new() constraint be removed, and a Factory Func<Type, object> be used instead? You can use (T) Activator.CreateInstance(typeof(T)) as a default and trade a little compiler safety for flexibility - particularly important if ConvertDocument can be switched out.

**Comment by chriseldredge** [comment]
LuceneDataProvider already has overloads for AsQueryable and OpenSession that accept a Func&lt;T> delegate for creating new instances of T.

I'm looking at making IDocumentMapper and related interfaces and classes public and providing overloads on LuceneDataProvider to let you specify your own implementation.

**Comment by chriseldredge** [comment]
I've added overloads to LuceneDataProvider that accept an IDocumentMapper from the client. I've also made ReflectionDocumentMapper and ReflectionFieldMapper public with virtual implementations to facilitate decorating their behavior. (see commit c3702cd89796f732aef98d3b03067f6ac87d0c77)

A preview package has been pushed to nuget.org at http://nuget.org/packages/Lucene.Net.Linq/3.1.44-preview

**Comment by mcintyre321** [comment]
Downloaded! Thanks!

**Comment by mcintyre321** [comment]
Thanks! [My document db](https://github.com/mcintyre321/PieDb) has search :)
