### ISSUE TITLE
Search ModelType1 but also return results of ModelType2

### ISSUE THREAD

**Issue by mouhong** [chriseldredge/Lucene.Net.Linq#31]
I'm using Lucene.Net.Linq v3.1.48

I make the LuceneDataProvider a singleton. I checked the index folder and found that all index files are in the same folder. Now if I index many Majors and Universities, and query it like this:

``` csharp
// The returned majors contains both Majors and Universities
// (the CLR type is Major, but it returns Universities as Majors), 
// but I just want it to return Majors, not Universites
var majors = provider.OpenSession<Major>().Query();
var universities = provider.OpenSession<University>().Query();
```

for example, the first line above will return these data:

``` javascript
Major { Code = "0001", Name = "Major 1", MajorSpecificField1 = "major 1" } // correct
Major { Code = "0002", Name = "Major 2", MajorSpecificField1 = "major 2" } // correct
Major { Code = "0011", Name = "University 1", MajorSpecificField1 = null } // incorrect
```

NOTE: The Majors and Universities are indexed using a same LuceneDataProvider. And the Major and University both have "Name" and "Code" properties. I think this might be the cause?

``` csharp
public class Major {
    [Field(Key = true)]
    public string Code { get; set; }
    public string Name { get; set; }
    // other properties 
}

public class University {
    [Field(Key = true)]
    public string Code { get; set; }
    public string Name { get; set; }
    // other properties
}
```

Check this gist: https://gist.github.com/mouhong/5924744#file-program-cs

Any ideas? Thanks

**Comment by chriseldredge** [comment]
The problem is that Lucene.Net.Linq does not add any additional fields to the underlying index that indicate the object type. You must distinguish between different types by either using a different field name for each different type or by adding a DocumentKey attribute to each type. See [Samples/DocumentKeys.cs](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/DocumentKeys.cs) for code samples.

**Comment by mouhong** [comment]
@chriseldredge Good! The sample is exactly what I need. Thanks! 
But I think this is a bit confusing, especially to new users. Can we use "One Entity Type One Lucene Directory" approach? For example, the directory of the LuceneDataProvider is /Indexes, then the index directory for Article is /Indexes/Artices, and the index directory for Product is /Indexes/Products.

**Comment by chriseldredge** [comment]
You are certainly welcome to take this approach on your own, but there are many other Lucene based frameworks, such as Solr, that use a single index to hold different types of documents. Perhaps some improvements can be made to the Lucene.Net.Linq documentation to bring this to the attention of new users.

**Comment by mouhong** [comment]
Or maybe include a build-in invisible field (e.g., $type) to indicate the entity type by default? Cos I think using Id as the key for almost all entity types is very common.

**Comment by chriseldredge** [comment]
The library is intended to read and write indexes in a compatible manner with other programs and tools so transparency is paramount. Adding magic fields to the index would break this compatibility. Again, you can already do that using `[DocumentKey(FieldName = "$type", Value = "Major")]` so to me this is more of a documentation issue.

**Comment by mouhong** [comment]
Yea, ok. Anyway, this works. Thanks :)
