### ISSUE TITLE
IEnumerable and fluent interface

### ISSUE THREAD

**Issue by uksus70** [chriseldredge/Lucene.Net.Linq#34]
Cannot configure IEnumerable field using fluent interface.
Property:
`public IEnumerable<String> Tags { get; set; }`
Mapping:
`map.Property(x => x.Tags);`
The field doesn't appear in the index after adding a document.

**Comment by chriseldredge** [comment]
Thanks for reporting this. A fix is in f130a1908e8119c5c23d30eb252a7af3e5705a11.

**Comment by uksus70** [comment]
Thanks! And when is it supposed to appear in NuGet?

**Comment by chriseldredge** [comment]
Perhaps tomorrow, perhaps next week.

**Comment by chriseldredge** [comment]
Released in 3.2.53.
