### ISSUE TITLE
Near real time search (NrtManager)

### ISSUE THREAD

**Issue by Loupi** [chriseldredge/Lucene.Net.Linq#37]
Hello Chris,

I recently found an interesting GitHub project for Lucene.NET:
https://github.com/NielsKuhnel/NrtManager/tree/master/Lucene.Net.Contrib.Management

Niels ported the NrtManager class (introduced in Lucene 3.5 I think) to .NET.
This class is usefull for managing single writer multiple reader scenarios without having to commit the index. 

There is also a background saver and a searcher manager.

**Comment by chriseldredge** [comment]
Are there examples of how this would be used, in Java or in c#?

**Comment by Loupi** [comment]
Mike McCandless wrote 2 blog posts on it: 
http://blog.mikemccandless.com/2011/11/near-real-time-readers-with-lucenes.html
http://blog.mikemccandless.com/2011/09/lucenes-searchermanager-simplifies.html

I can also send you a C# class I made that uses all of these altogether.

**Comment by chriseldredge** [comment]
`Context` was already doing similar stuff to share an IndexSearcher instance and refresh it on `Reload()`. 2a306b157cfc5a76dc41d3b2135e2672acbe0ccb improves performance by using `IndexReader.Reopen()` to reuse components from a previous reader.

Thanks for the idea.

I'll leave this open until it gets released on nuget.org.

**Comment by chriseldredge** [comment]
http://www.nuget.org/packages/Lucene.Net.Linq/3.2.57
