### ISSUE TITLE
Fluent mapping and AsQueryable/OpenSession inconsistency

### ISSUE THREAD

**Issue by uksus70** [chriseldredge/Lucene.Net.Linq#39]
I have created a fluent map:

```
ClassMap<Record> map = new ClassMap<Record>(Lucene.Net.Util.Version.LUCENE_30);
map.Property(…);
…
LuceneDataProvider provider = new …;
```

Then `provider.AsQueryable<Record>()` automatically uses my map. But `provider.OpenSession<Record>()` does not. I need to explicitly specify the document mapper: `provider.OpenSession<Record>(map.ToDocumentMapper())`

What's wrong am I doing or understanding?

**Comment by uksus70** [comment]
Seems like `provider.AsQueryable<Record>()` actually doesn't use the mapping automatically in fact, but use some default mapping settings instead. Whereas `provider.AsQueryable<Record>(map.ToDocumentMapper())` doesn't return any record.

What is the proper way to use fluent mapping?

**Comment by chriseldredge** [comment]
[Samples/FluentConfiguration](/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/FluentConfiguration.cs) contains a working example, so I would need to see a more complete code sample to help you.

`provider.AsQueryable<Record>(map.ToDocumentMapper())` is the correct overload to use when using ClassMap.

**Comment by uksus70** [comment]
```
    public class LuceneMappingStartupTask
    {

        public static IDocumentMapper<Record> RecordMapper;

        public void Run()
        {
            var map = new ClassMap<Record>(Lucene.Net.Util.Version.LUCENE_30);
            map.Key(x => x.Id).NotIndexed();
            map.Property(x => x.Type).NotAnalyzed().ConvertWith(new EnumConverter(typeof(RecordType)));
            map.Property(x => x.DateTag);
            map.Property(x => x.Language).NotAnalyzed();
            map.Property(x => x.Urls);//.ToField("Url").ConvertWith(new UriTypeConverter());
            map.Property(x => x.Subject);
            map.Property(x => x.Place);
            map.Property(x => x.Occasion);
            map.Property(x => x.Description);
            map.Property(x => x.Responsibles);
            map.Property(x => x.Book);
            map.Property(x => x.Beginning);

            RecordMapper = map.ToDocumentMapper();
        }
    }
```

And `provider.AsQueryable<Record>(LuceneMappingStartupTask.RecordMapper)` still returns no records.

**Comment by chriseldredge** [comment]
You are specifying `Key(x => x.Id).NotIndexed()`, but key fields must always be indexed to work correctly. You are getting no records because the query is including a clause like `Id:*` and it is not matching any documents because the field is not indexed and therefore always absent.

**Comment by uksus70** [comment]
Indeed! Thank you very much, now `provider.AsQueryable<Record>(LuceneMappingStartupTask.RecordMapper)` works as expected.
