### ISSUE TITLE
How to use delete?

### ISSUE THREAD

**Issue by mcintyre321** [chriseldredge/Lucene.Net.Linq#4]
thanks for your help so far. I've got stuck trying to remove/update items.

My PieReflection mapper sets a constant DocumentKey, so I'm thinking you remove, then add it again? It doesn't seem to be taking things out of the index... I suspect I am doing it wrong though...

```
private void UpdateDocumentInIndex<T>(PieDocument document) where T : new()
        {
            using (var session = _provider.OpenSession<T>(new PieReflectionDocumentMapper<T>((Version)Version.LUCENE_30, this)))
            {
                session.Delete((T) document.Data);
            }
            using (var session = _provider.OpenSession<T>(new PieReflectionDocumentMapper<T>((Version)Version.LUCENE_30, this)))
            {
                session.Add((T)document.Data);
            }
        }
```

**Comment by chriseldredge** [comment]
This should suffice:

```
private void UpdateDocumentInIndex<T>(PieDocument document) where T : new()
{
    using (var session = _provider.OpenSession<T>(new PieReflectionDocumentMapper<T>((Version)Version.LUCENE_30, this)))
    {
        session.Add((T)document.Data);
    }
}
```

As long as document has an equal key as the document it replaces, the session should automatically perform a delete on that key before adding the modified document.

You can try configuring Common.Logging and setting the level to TRACE to get some hints as to what the session is doing. See [App.config](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/App.config) for an example configuration.

**Comment by mcintyre321** [comment]
Yep user error, not keeping track of my virtual Id properties properly, thanks again.
