### ISSUE TITLE
Exception is thrown trying to run example from readme

### ISSUE THREAD

**Issue by dziedrius** [chriseldredge/Lucene.Net.Linq#42]
I'm trying to run example from readme (it is a bit outdated) and it fails with this:

>   Sequence contains more than one element
> at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at Lucene.Net.Linq.Util.AnalyzerExtensions.Analyze(Analyzer analyzer, String fieldName, String pattern)
>    at Lucene.Net.Linq.Mapping.ReflectionFieldMapper`1.EvaluateExpressionToStringAndAnalyze(Object value)
>    at Lucene.Net.Linq.Mapping.ReflectionFieldMapper`1.CreateRangeQuery(Object lowerBound, Object upperBound, RangeType lowerRange, RangeType upperRange)
>    at Lucene.Net.Linq.Translation.TreeVisitors.QueryBuildingExpressionTreeVisitor.CreateRangeQuery(IFieldMappingInfo mapping, QueryType queryType, LuceneQueryPredicateExpression lowerBoundExpression, LuceneQueryPredicateExpression upperBoundExpression)
>    at Lucene.Net.Linq.Translation.TreeVisitors.QueryBuildingExpressionTreeVisitor.VisitLuceneQueryPredicateExpression(LuceneQueryPredicateExpression expression)
>    at Lucene.Net.Linq.Clauses.TreeVisitors.LuceneExpressionTreeVisitor.VisitExtensionExpression(ExtensionExpression expression)
>    at Remotion.Linq.Clauses.Expressions.ExtensionExpression.Accept(ExpressionTreeVisitor visitor)
>    at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
>    at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitBinaryExpression(BinaryExpression expression)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Lucene.Net.Analysis.Standard;
using Lucene.Net.Index;
using Lucene.Net.Linq;
using Lucene.Net.Linq.Mapping;
using Lucene.Net.Store;
using ServiceStack.Text;

namespace ConsoleApplication2
{  
    public class Article
    {
        public string Author { get; set; }
        public string Title { get; set; }
        public DateTimeOffset PublishDate { get; set; }

        // Stores the field as a NumericField
        [NumericField]
        public long Id { get; set; }

        // Stores the field as text
        public int IssueNumber { get; set; }

        [Field(IndexMode.NotIndexed, Store = StoreMode.Yes)]
        public string BodyText { get; set; }

        // Maps to field "text"
        [Field("text", Store = StoreMode.No)]
        public string SearchText
        {
            get { return string.Join(" ", new[] { Author, Title, BodyText }); }
        }

        // Add IgnoreFieldAttribute to properties that should not be mapped to/from Document
        [IgnoreField]
        public string IgnoreMe { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var directory = new RAMDirectory();
            var writer = new IndexWriter(directory, new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30), IndexWriter.MaxFieldLength.UNLIMITED);

            var provider = new LuceneDataProvider(directory, writer.Analyzer, Lucene.Net.Util.Version.LUCENE_30, writer);

            // add some documents
            using (var session = provider.OpenSession<Article>())
            {
                session.Add(new Article { Author = "John Doe", BodyText = "some body text", PublishDate = DateTimeOffset.UtcNow });
            }

            var articles = provider.AsQueryable<Article>();

            var threshold = DateTimeOffset.UtcNow.Subtract(TimeSpan.FromDays(30));

            var articlesByJohn = from a in articles
                                 where a.Author == "John Doe" && a.PublishDate > threshold
                                 orderby a.Title
                                 select a;

            var searchResults = from a in articles
                                where a.SearchText == "some search query"
                                select a;

            Console.WriteLine(articlesByJohn.Dump());
            Console.WriteLine(searchResults.Dump());
            Console.Read();
        }
    }
}

```

**Comment by chriseldredge** [comment]
Please refer to the examples in [Lucene.Net.Linq.Tests/Samples](/themotleyfool/Lucene.Net.Linq/tree/master/source/Lucene.Net.Linq.Tests/Samples).
