### ISSUE TITLE
Unable to use natural sorting with a property assigned a Converter or Format

### ISSUE THREAD

**Issue by cherrydev** [chriseldredge/Lucene.Net.Linq#44]
This should be a fairly common issue:
I have a date field that I'm storing in the index using the Lucene.Net.Document.DateTools methods.  This requires me to place a Converter in the mapping of the field.  Unfortunately, this cause Lucene.Net.Linq to use a custom comparator for the sorting on that field and it's excruciatingly slow (about 5s to sort a few thousand records)!  If most data in a Lucene index is (or should be) stored in a way that can be naturally sorted (if sorting is anticipated on that field) there should be a way to disable this custom comparator, but unfortunately there is no way to disable the custom comparator in the presence of a converter in the mapping.

I've dug through the classes that ultimately trigger this behaviour, between ReflectionDocumentMapper and ReflectionFieldMapper and there's a whole lot of static private methods that would need to re-implemented if I wanted to map a single field with a custom subclass of ReflectionFieldMapper.

I've looked at trying to do something with ClassMap, but I can't subclass PropertyMap because all of the constructors are internal...

In all, I'm stumped.  Any clues where I could work around this?

If you think a new extension point could be made to remedy this, do you think it should be specific to the sorting behaviour (for example, a UseNaturalSorting property of FieldAttribute) or a lower-level extension point to be able to provide your own mapper?

Incidentally, this happens even if you just apply a Format option instead of a Converter (since I figure it will make a converter from the format internally.

An example of the final Lucene query it generates looks like:

+(-validstate:999 _:_) +(+program:221) sort by <custom:"date": Lucene.Net.Linq.Search.NonGenericConvertableFieldComparatorSource>!.Take(10)

**Comment by cherrydev** [comment]
Incidentally, ordinal and range queries work perfectly when using a Format or Converter on a DateTime field.

Btw, I tried just using the date field as a string and parse/formatting it on the client side.  That fixes the sorting problem, but Lucene.Net.Linq gets confused when you try to do an ordinal (or presumably range) query on a string, so that turned out to not actually be a solution either.

**Comment by chriseldredge** [comment]
I have used DateTime or DateTimeOffset and stored them as numeric fields and haven't noticed any major performance issues. However, I'll try to reproduce this issue to see if I can find a bottleneck.

**Comment by cherrydev** [comment]
Please make note that I'm not saving the dates as a NumericField, but just as regular fields using the DateTools static methods.

**Comment by chriseldredge** [comment]
I wrote a [test case](https://gist.github.com/chriseldredge/7517971) to see if I could find a performance problem, and I found that native sorting and sorting with IComparable take about the same amount of time (476ms vs 499ms to sort 25,000 fields).

In any case, the test code shows a somewhat round-about method of preventing IComparable sort from being triggered. It seems like a good idea for the client to be able to suppress this behavior and use simple alphanumeric sorting, so I'll keep this open as a request to do that.

**Comment by chriseldredge** [comment]
Actually modifying the test a little to not retrieve all documents, but only the first, and rerunning the queries to take advantage of a warm field cache shows native executes in 2ms vs 22ms for IComparable.

That is a big difference. I've used a [caching converter](https://github.com/themotleyfool/NuGet.Lucene/blob/master/source/NuGet.Lucene/Mapping/CachingVersionConverter.cs) in one of my projects to improve performance, but still it makes sense to offer a simple way to use native sorting.

**Comment by cherrydev** [comment]
Sorry I haven't left a comment about this for a while.  But yes, that's EXACTLY the issue: using the custom comparators requires Lucene to fetch the documents because it can't use the contents of the index.  Incidentally, I haven't tried this, but I assume that the custom comparators will only work on fields that are stored.

**Comment by chriseldredge** [comment]
I believe the custom sort implementation does not work much differently than native fields and should work on fields that are indexed but not stored, but I haven't tested that either. While it's true each field for each document in the index must be loaded, this isn't much different from how the native implementations work. I think the performance penalty is in actually converting each field to its complex type which is where caching can mitigate the problem. This seems to be confirmed by the tests I ran today: 20ms of overhead compared to native after the field cache is warm.

**Comment by chriseldredge** [comment]
3dc95851d7b30ba195f4fe23ee43953138d74887 adds NativeSort as an option on attribute/fluent mappings. Disabled by default.

**Comment by chriseldredge** [comment]
Released: https://nuget.org/packages/Lucene.Net.Linq/3.2.54
