### ISSUE TITLE
RangeQueries on NumericFields are translated to lucene as 2 seperate NumericRangeQueries, greatly decreasing performance.

### ISSUE THREAD

**Issue by gshark4321** [chriseldredge/Lucene.Net.Linq#46]
Range queries such as this (Time is a NumericField):
(from a in data
where
     a.Time >= startTime
     && a.Time < endTime
select a)
.Take(10);

are translated into two separate range queries:
+Time:{635197536000000000 TO 3155378975999999999] +Time:[288000000000 TO 635197536600000000]

eg) startTime TO EndOfTime AND BeginningOfTime TO endTime

Ideally, it should be translated into a single range query:
+Time:{635197536000000000 TO 635197536600000000] 

eg) startTime TO endTime

When the index is large, this causes a large performance penalty. 
On tests of an index with 50million documents:
Using a single range query  - a range that covers 1million document takes 100ms.
Using the double range query pattern described above - a range that covers 1 million documents take 3 seconds.

As the range covers more of available documents, the performance penalty decreases, but is still quite noticeable.

**Comment by chriseldredge** [comment]
Yes, I was aware of this when I implemented it, but figured I'd come back to optimize it, and hadn't actually attempted to determine if there was a penalty in the first place.

Thanks for the report. I'm not working a whole lot on this project at the moment, so can't say when I'd have a fix ready by.

**Comment by chriseldredge** [comment]
See f2c6b71e8891bd77223c98f8d9b9f523c616fd0a. It should capture the basic case.

The optimization will only work currently if both bounds of the range query appear as the left and right sides of a BinaryExpression.

Later I might try to improve this so more complex nesting of clauses are also optimized.

**Comment by gshark4321** [comment]
This is awesome! Thanks!

**Comment by gshark4321** [comment]
Can you make a release soon?

**Comment by chriseldredge** [comment]
Yes, working through one remaining issue and planning to release within the next 7 days.

**Comment by chriseldredge** [comment]
Released: https://nuget.org/packages/Lucene.Net.Linq/3.2.54
