### ISSUE TITLE
Question: Is there an attribute or fluent syntax for boosting documents in an index?

### ISSUE THREAD

**Issue by danludwig** [chriseldredge/Lucene.Net.Linq#47]
I looked at the source, unit tests, and limited docs, but couldn't find an API for this. Is there one?

**Comment by chriseldredge** [comment]
Not currently. This could be added with an overload to `ISession.Add(T item, float boost)`.

**Comment by chriseldredge** [comment]
Added in c267b7df8dff75b46292942cf4feb23743b62927

**Comment by chriseldredge** [comment]
Released in https://github.com/themotleyfool/Lucene.Net.Linq/releases/tag/v3.3.2
