### ISSUE TITLE
Fluent mappings does not use Custom converter for queries

### ISSUE THREAD

**Issue by TheoAndersen** [chriseldredge/Lucene.Net.Linq#49]
I'm trying to save and query a DateTime as a numerical field (for performance). So i've added a custom TypeConverter to do the conversion, but it seems that, it only uses the converter when adding it.
When querying it defaults to the built in DateTimeConverter and fails with a FormatException: "String was not recognized as a valid DateTime".
 And should'nt the value be fetched as a long, being that its defined as a numericalField?

The same thing works when using Attributes, and uses the custom converter both for adding and querying (and passes in a long/int64)

I've created unit tests for the failing (fluent) and working (attributes) example in this gist
https://gist.github.com/TheoAndersen/8236625

It can also be found in this commit on my fork
https://github.com/TheoAndersen/Lucene.Net.Linq/commit/408bab01994a52ebcf98ce58a13c6b3823a9250d

/Theo

**Comment by chriseldredge** [comment]
I wrote a comment on your gist. When using fluent mapping you must use an overload of `AsQueryable<T>` that accepts the `IDocumentMapper<T>` from your class map.

**Comment by TheoAndersen** [comment]
Ahh that explains it... Thanks for the quick response
