### ISSUE TITLE
NumericField(Key = true) never returned from Query

### ISSUE THREAD

**Issue by azhmur** [chriseldredge/Lucene.Net.Linq#5]
I have simple class like:

public class Data
{
  [NumericField(Key=true)]
  public Id { get; set; }
  [Field]
  public Name { get; set;}
}

It is never selected from catalog because executionContext.Filter passed to searcher in LuceneQueryExecutor.ExecuteCollection contains filter (+Id:*) that filters out all results.

Changing it to ordinary Field fixes the issue.

**Comment by chriseldredge** [comment]
Confirmed. Working on a fix.

**Comment by chriseldredge** [comment]
Fixed in 3.1.45, just published to NuGet Gallery. Thanks for reporting.
