### ISSUE TITLE
Is there posibility to configure AllowSpecialCharacters?

### ISSUE THREAD

**Issue by mykhayloArtymyshyn** [chriseldredge/Lucene.Net.Linq#54]
How can set true to LuceneQueryPredicateExpression.AllowSpecialCharacters?

**Comment by chriseldredge** [comment]
See [AllowSpecialCharactersTests](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Integration/AllowSpecialCharactersTests.cs#L32) for an example.

**Comment by mykhayloArtymyshyn** [comment]
Thans
