### ISSUE TITLE
Fluent mappings aren't using per-field analyzers

### ISSUE THREAD

**Issue by mattjohnsonpint** [chriseldredge/Lucene.Net.Linq#55]
When using the fluent mappings, I am getting no results back when searching on a string containing at least one upper-case letter.  It would appear that even though the `ClassMap` is properly setting `CaseInsensitiveKeywordAnalyzer`, this isn't being copied into the `PerFieldAnalyzer` properly.

Failing unit test:  https://gist.github.com/mj1856/9147377

**Comment by chriseldredge** [comment]
Thanks for reporting. I moved your code to encapsulate the behavior and noticed it needed to be added for Key properties as well. I'll close the issue after releasing to nuget.org.

**Comment by chriseldredge** [comment]
Fix deployed in http://www.nuget.org/packages/Lucene.Net.Linq/3.2.57
