### ISSUE TITLE
Collection fields

### ISSUE THREAD

**Issue by mattjohnsonpint** [chriseldredge/Lucene.Net.Linq#58]
It would appear I can only map a collection property as a field if it is declared as `IEnumerable<T>`.  It should really support any type that _inherits_ from `IEnumerable<T>`, including lists, arrays, `IList<T>`, etc...

**Comment by chriseldredge** [comment]
There's a TODO [here](https://github.com/themotleyfool/Lucene.Net.Linq/blob/43367233765174f4f4ef1c1716eeffe7bd0a1f31/source/Lucene.Net.Linq/Mapping/CollectionReflectionFieldMapper.cs#L26) that would need some attention.

There may be other places where changes are required.

**Comment by chriseldredge** [comment]
See also #32.

**Comment by mattjohnsonpint** [comment]
Thanks.  If I get some time, I'll see if I can tackle that todo and send a PR.
