### ISSUE TITLE
How To Get DocID ?

### ISSUE THREAD

**Issue by temperory** [chriseldredge/Lucene.Net.Linq#59]

**Comment by chriseldredge** [comment]
You can do this by implementing your own subclass of `ReflectionDocumentMapper<T>` as in [this example](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/MoreLikeThisSample.cs#L70).

Keep in mind Document IDs are only valid for the life of the current reader, so you probably don't want to use them for anything outside of the scope of methods you override in your DocumentMapper.
