### ISSUE TITLE
Equivalent to IgnoreAttribute for Fluent Mapping

### ISSUE THREAD

**Issue by kevinreece** [chriseldredge/Lucene.Net.Linq#61]
Hi,

How do you ignore properties when using Fluent mapping?

I am unable to use the attributes due to using EF6; before considering DTO classes I wanted to try and use this feature but I am having problems.

Thanks

**Comment by chriseldredge** [comment]
Simple omitting a property should cause it not to be mapped by the fluent mapping.

Is this not the case?
