### ISSUE TITLE
No .NET 4.5 support

### ISSUE THREAD

**Issue by WizX20** [chriseldredge/Lucene.Net.Linq#67]
Just tried the NuGet package with a 4.5 project and alas this does not work. It does install but since Remotion.Linq has a 4.5 version we get all kinds of reference exceptions.

I downloaded the project, set the framework to 4.5 for the project and updated the Remotion.Linq package to version 1.15.15.0. They apparently made some breaking changes because Remotion.Linq.Utilities no longer contains the RegistryBase (is used for example in Lucene.Net.Linq.ScalarResultHandlers.ScalarResultHandlerRegistry).

**Comment by chriseldredge** [comment]
Yeah, the remotion team unfortunately hasn't been enlightened about semantic versions.

Use the Package Manager Console to install Remotion.Linq version 1.15.9.0, then install Lucene.Net.Linq, and you should be good to go.

I'll keep this open to put a tighter constraint on the versions of Remotion.Linq that are supported by Lucene.Net.Linq.

**Comment by chriseldredge** [comment]
Lucene.Net.Linq has a version constraint that ensures Remotion.Linq 1.13.183 or later, but nothing after 1.15.10 is installed. Fix will be in Lucene.Net.Linq 3.3.2.

**Comment by chriseldredge** [comment]
Released in https://github.com/themotleyfool/Lucene.Net.Linq/releases/tag/v3.3.2

This should install the right stuff when you install Lucene.Net.Linq and prevent you from upgrading Remotion.Linq past 1.15.9.

**Comment by WizX20** [comment]
@chriseldredge Awesome! Thank you.
