### ISSUE TITLE
TextFragments and Highlighting Support

### ISSUE THREAD

**Issue by denniseffing** [chriseldredge/Lucene.Net.Linq#69]
It would appear that there is no way to generate TextFragments for the Highlighter of Lucene without implementing a new IndexSearcher, QueryParser and TokenStream which would completely bypass your Lucene.Net.Linq Library/LuceneDataProvider-Concept.

Are there any plans for supporting this or would you mind looking into this?

**Comment by chriseldredge** [comment]
This could probably be accomplished in a similar method as in [MoreLikeThisSample](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/MoreLikeThisSample.cs).

I haven't worked with TextFragments but this gives you an extension point where you can perform additional operations while mapping a result, store them in memory and retrieve them after your query executes.

I don't have additional plans for building this directly into the LINQ query syntax.
