### ISSUE TITLE
LuceneDataSource gets corrupted on session rollback

### ISSUE THREAD

**Issue by azhmur** [chriseldredge/Lucene.Net.Linq#7]
It may be not an issue but misunderstanding, but i consider LuceneDataSource as a long living object while Sessions as short-lived. Now if session fails to commit it calls close on parent data source writer, thus making it unusable any further.
Is it expected to create LinqDataSource per session?

**Comment by chriseldredge** [comment]
Looks like a bug. I didn't realize that IndexWriter.Rollback() closes the writer.
