### ISSUE TITLE
Automatic / Reflection mapping

### ISSUE THREAD

**Issue by ronnyek** [chriseldredge/Lucene.Net.Linq#76]
Not a bug, but more a question...

I've tried to dig through the unit tests to find example of this... I want to basically hand over simple objects (that come from 3rd party so they cant be marked up with lucene specific attributes).

I'd like to basically be able to hand lucene these simple objects and just index everything.

**Comment by chriseldredge** [comment]
Sorry for not responding sooner. There is an example of configuring mappings for objects outside of your control here:

https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq.Tests/Samples/FluentConfiguration.cs
