### ISSUE TITLE
Not analyzed boolean field not working

### ISSUE THREAD

**Issue by mouhong** [chriseldredge/Lucene.Net.Linq#8]
``` csharp
[Field(IndexModel.NotAnalyzed)]
public bool Flag { get; set; }

var query = session.Query().Where(x => x.Flag == true); // Always returns nothing
```

Expected: return results that Flag is true
Actual: return nothing

I checked the source code, and found that:
In the field mapper, BooleanConverter converts true value to string "True".
In the linq provider part, it translates Where(x => x.Flag == true) to lucene query: Flag: true. Note that it's "true", not "True".

So the query returns empty result.

Because by default the boolean field is "Analyzed", so this problem only happens when the field is manually set to IndexMode.NotAnalyzed.

**Comment by chriseldredge** [comment]
This test passes on master:

```
[TestFixture]
public class NotAnalyzedBooleanTests
{
    private Directory directory;
    private LuceneDataProvider provider;

    public class Item
    {
        [Field(IndexMode.NotAnalyzed)]
        public bool Flag { get; set; }
    }

    [SetUp]
    public void SetUp()
    {
        directory = new RAMDirectory();
        provider = new LuceneDataProvider(directory, Version.LUCENE_30);
    }

    [Test]
    public void IsNotCaseSensitive()
    {
        using (var session = provider.OpenSession<Item>())
        {
            session.Add(new Item {Flag = true});
        }

        var single = provider.AsQueryable<Item>().Single(i => i.Flag == true);

        Assert.That(single, Is.Not.Null);
    }
}
```

Which version are you using? Are you passing in your own Analyzer or letting Lucene.Net.Linq build one for you?

**Comment by mouhong** [comment]
I also tested it in master (revision 1a4af91: Avoid running patterns through QueryParser.Escape for NumericFields since the patterns are not parsed. Fixes #6)

Could you try this in console? No article is retrieved in my PC:

``` csharp
static void Main(string[] args)
{
    LuceneNetLinqTest();

    Console.WriteLine("Press any key to continue...");
    Console.ReadKey();
}

static void LuceneNetLinqTest()
{
    var provider = new LuceneDataProvider(new RAMDirectory(), new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30), Lucene.Net.Util.Version.LUCENE_30);

    using (var session = provider.OpenSession<Article>())
    {
        session.Add(new Article
        {
            IsVisibleToAll = true,
        });
        session.Add(new Article
        {
            IsVisibleToAll = false,
        });
        session.Add(new Article
        {
            IsVisibleToAll = true,
        });
        session.Commit();
    }

    using (var session = provider.OpenSession<Article>())
    {
        var articles = session.Query().Where(x => x.IsVisibleToAll).ToList();
        foreach (var article in articles)
        {
            Console.WriteLine(article.IsVisibleToAll);
        }
    }
}
```

**Comment by mouhong** [comment]
It's strange that I tried you test case and it did pass, but my console test failed. (I referenced the Lucene.Net.Linq.dll from the Debug folder of my master clone) Don't know what's wrong

**Comment by chriseldredge** [comment]
The StandardAnalyzer is the problem. Try using a constructor for LuceneDataProvider that does not take an Analyzer and it create an appropriate one for you.

On Mar 4, 2013, at 9:33 PM, "Mouhong Lin" <notifications@github.com<mailto:notifications@github.com>> wrote:

I also tested it in master (revision 1a4af91https://github.com/themotleyfool/Lucene.Net.Linq/commit/1a4af91: Avoid running patterns through QueryParser.Escape for NumericFields since the patterns are not parsed. Fixes #6https://github.com/themotleyfool/Lucene.Net.Linq/issues/6)

Could you try this in console? No article is retrieved in my PC:

static void Main(string[] args)
{
    LuceneNetLinqTest();

```
Console.WriteLine("Press any key to continue...");
Console.ReadKey();
```

}

static void LuceneNetLinqTest()
{
    var provider = new LuceneDataProvider(new RAMDirectory(), new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30), Lucene.Net.Util.Version.LUCENE_30);

```
using (var session = provider.OpenSession<Article>())
{
    session.Add(new Article
    {
        IsVisibleToAll = true,
    });
    session.Add(new Article
    {
        IsVisibleToAll = false,
    });
    session.Add(new Article
    {
        IsVisibleToAll = true,
    });
    session.Commit();
}

using (var session = provider.OpenSession<Article>())
{
    var articles = session.Query().Where(x => x.IsVisibleToAll).ToList();
    foreach (var article in articles)
    {
        Console.WriteLine(article.IsVisibleToAll);
    }
}
```

}

**Comment by mouhong** [comment]
Cool! It works. Thanks
