### ISSUE TITLE
Wildcard, Prefix and Fuzzy queries return no results

### ISSUE THREAD

**Issue by rowandh** [chriseldredge/Lucene.Net.Linq#83]
Several type of Lucene queries are parsed incorrectly by FieldMappingQueryParser:
- Wilcard Query
- Prefix Query
- Fuzzy Query

To reproduce:
- Pass a wildcard query eg. "test*" into FieldMappingQueryParser.Parse
- Observe that the parsed query is this string: "Lucene.Net.Linq.FieldMappingQueryParser`1[[YourProject.YourDocument, YourProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].DEFAULT_FIELD:test*"

This is due to the search field only being overridden with DefaultSearchProperty on certain QueryParser overrides:
- GetFieldQuery(string field, string queryText)
- GetRangeQuery(string field, string part1, string part2, bool inclusive)

but not:
- GetFieldQuery(string field, string queryText, int slop)
- GetWildcardQuery(String field, String termStr)
- GetPrefixQuery(String field, String termStr)
- GetFuzzyQuery(String field, String termStr, float minSimilarity)

Solution:
We could override these methods and use them to remap the default search field. But this beholds us to any changes in the internals of QueryParser.

The correct solution is to inject the default search field to FieldMappingQueryParser's constructor rather than set it as a property.

Then we can add an override CreateQueryParser<T>(string defaultField) to LuceneDataProvider, and remove the DefaultSearchProperty property from FieldMappingQueryParser.

I don't see any advantage to using a property to set this field - if a user wants to dynamically change the default search field for some reason, they can just use the factory method to create a new query parser.

However, this fix breaks backwards compatibility for anyone who is already using DefaultSearchProperty (although many of their queries will already be returning no results).

There is an interim solution:
- Create the overrides for the Lucene query methods - this fixes the broken parses for FieldMappingQueryParser
- Add a constructor override to FieldMappingQueryParser to allow injection of a default search field
- Add a method override CreateQueryParser<T>(string defaultField) on LuceneDataProvider
- Deprecate DefaultSearchProperty
- Deprecate the FieldMappingQueryParser constructor without a default field

I'm not sure how keen you are to introduce a change that breaks backwards compatibility, so I'll submit a PR shortly with my interim solution and tests.

**Comment by rowandh** [comment]
Missed some test cases in my initial PR. Somehow skipped over the fact that this affects all queries and not just queries where DefaultSearchProperty is set. I'll create another one.

**Comment by chriseldredge** [comment]
Merged to master.

**Comment by chriseldredge** [comment]
This was released in 3.6.0 today on nuget.org.
