### ISSUE TITLE
Lucene search;find only recently added data

### ISSUE THREAD

**Issue by Fibinacci** [chriseldredge/Lucene.Net.Linq#88]
I am trying to use Lucene.Net.Linq when i am writing C# Web.Api. I can insert data. But ,while searching, I can reaches only  recently added data. Not find previously added data. In the file directory, and commit occurs after all the data I added. Like (_0.cfs , _0_1.del ,_1.cfs , _1_1.del  _2.cfs , _2_1.del,.... ,segments.gen,segments_7).

I looked at the Lucene Index Toolbox program to this file. But when I tried to make a call, you can access only the recently data in the same way. That is the database example on Luke
![capture](https://cloud.githubusercontent.com/assets/12153606/9490941/23634abc-4bf4-11e5-87b7-8d161ee4d9af.PNG) 
I can acccess only "kemal".  This word type = "NameWord".

I noticed that, taking the same Id(Id=0) of data I was each added. How to assign values automatically id.

```
    public class NameWord : IWord
   {
    [NumericField]
    public int Id { get; set; }
    [Field]
    public string Word { get; set; }
}
```

**Comment by chriseldredge** [comment]
I'm not sure I understand what you are trying to do. Are you saying that you are adding many documents but when you query you can only retrieve the most recently added document?

Can you provide example code that is inserting documents and then also example code of how you are querying?
