### ISSUE TITLE
Search Generated Query

### ISSUE THREAD

**Issue by egorppv** [chriseldredge/Lucene.Net.Linq#94]
Can't find any way, how can I see generated query by lucene.net.linq.
May be it is not a bug, but a good improvement could be.

**Comment by chriseldredge** [comment]
You can get the generated query by using [LuceneQueryStatistics.Query](https://github.com/themotleyfool/Lucene.Net.Linq/blob/master/source/Lucene.Net.Linq/LuceneQueryStatistics.cs#L41).

Example:

``` c#
LuceneQueryStatistics stats = null;

provider
  .AsQueryable<SampleDocument>()
  .CaptureStatistics(s => { stats = s; })
  .Where(d => d.SearchText == "foo")
  .Skip(20)
  .Take(20)
  .ToList();

var generatedQuery = stats.Query;
```
